package courseapp

import (
	"os"
	"path/filepath"
	"testing"
)

func TestFixtureUsesTLSFromTierTwoOnward(t *testing.T) {
	// Release data moved behind TLS in Tier 2 and no later tier moves it back.
	// A tier added later that quietly went back to plain HTTP would be a
	// regression in a published control, so this is asserted rather than
	// assumed.
	for _, id := range []string{
		"tier-02/plaintext-inspection", "tier-03/hostile-image",
		"tier-04/hostile-release", "tier-04/replay-release",
	} {
		if !fixtureUsesTLS(id) {
			t.Errorf("%s should use the verified connection", id)
		}
	}
	for _, id := range []string{"tier-00/altered-image", "tier-00/device-id-spoofing"} {
		if fixtureUsesTLS(id) {
			t.Errorf("%s predates TLS and must stay on plain HTTP", id)
		}
	}
}

func TestFixtureCommandRecordsTheImageSelector(t *testing.T) {
	// The evidence record has to name the command that reproduces the run. A
	// Tier 3 run without its selector is not reproducible, because it does not
	// say which of the four images was published.
	a := &app{}
	got := a.fixtureCommand("tier-03/hostile-image", "wrong-key")
	want := "./course attack run tier-03/hostile-image --execute tier-03/hostile-image --image wrong-key"
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
	got = a.fixtureCommand("tier-00/altered-image", "")
	want = "./course attack run tier-00/altered-image --execute tier-00/altered-image"
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHostileImagesDifferFromTheGoodOne(t *testing.T) {
	// Both derivations must actually change the bytes. A modified image that
	// happened to be identical, or a truncation of zero bytes, would produce a
	// fixture that publishes a perfectly good release and a Learner watching
	// for a refusal that never comes.
	dir := t.TempDir()
	good := filepath.Join(dir, "good.bin")
	original := make([]byte, 0x9000)
	for i := range original {
		original[i] = byte(i)
	}
	if err := os.WriteFile(good, original, 0o600); err != nil {
		t.Fatal(err)
	}

	modified := filepath.Join(dir, "modified.bin")
	if err := deriveModified(good, modified); err != nil {
		t.Fatal(err)
	}
	changed, err := os.ReadFile(modified)
	if err != nil {
		t.Fatal(err)
	}
	if len(changed) != len(original) {
		t.Errorf("a modified image should be the same length, got %d want %d", len(changed), len(original))
	}
	if changed[0x8000] == original[0x8000] {
		t.Error("the modified image is identical to the good one")
	}

	truncated := filepath.Join(dir, "truncated.bin")
	if err := deriveTruncated(good, truncated); err != nil {
		t.Fatal(err)
	}
	short, err := os.ReadFile(truncated)
	if err != nil {
		t.Fatal(err)
	}
	if len(short) >= len(original) {
		t.Errorf("a truncated image should be shorter, got %d want less than %d", len(short), len(original))
	}
}

func TestDerivationsRefuseAnImageTooSmallToSpoil(t *testing.T) {
	dir := t.TempDir()
	tiny := filepath.Join(dir, "tiny.bin")
	if err := os.WriteFile(tiny, []byte("too short"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := deriveModified(tiny, filepath.Join(dir, "a.bin")); err == nil {
		t.Error("modifying an image smaller than the offset should fail loudly")
	}
	if err := deriveTruncated(tiny, filepath.Join(dir, "b.bin")); err == nil {
		t.Error("truncating an image shorter than the cut should fail loudly")
	}
}

func TestOnlyTheReleaseRoleHasAPublicHalf(t *testing.T) {
	// The attacker key is generated by the same command and is exactly as
	// valid. What must never happen is a build reading its public half, so the
	// roles are asserted here rather than left to the code path that happens to
	// call writePublicKey.
	if _, ok := signingRoles["release"]; !ok {
		t.Error("the release role must exist")
	}
	if _, ok := signingRoles["attacker"]; !ok {
		t.Error("the attacker role must exist")
	}
	if len(signingRoles) != 2 {
		t.Errorf("a third key role needs a decision about whether a build may read it, got %d", len(signingRoles))
	}
}
